### ISSUE TITLE
biocurator

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/pyphetools#107]
The biocurator string needs to have the date, e.g.
ORCID:0000-0000-0000-0000[2024-04-01]
currently, the date is not being added to the string. We can add today's date on the HPOA creation script

**Comment by matentzn** [comment]
As a suggestion for future annotation file formats it would be beneficial to split these into two fields, as we now have to have specific etl code to integrate the annotations into a knowledge graph. We have a lot of annotations to orcids, and if we want to aggregate across these, like in "counting how many contributions", we cant have the date in that string as well.

**Comment by pnrobinson** [comment]
Well, it would be difficult with shell commands but trivial for a python script to separate the ORCIDs from the dates... I do not think we want to have separate columns, because now at least we are recording updates by adding a second CURIE[date] to the annotation entry. 
I think the main use case is to count contributions, and this will become more important moving forward because phenopackets will allow us to democratize the process to some extent. I would be fine with removing the dates and the amendations, it is not mission critical and maybe we should not overcomplicate things. I do not know if external software is depending on the current format thougb

**Comment by pnrobinson** [comment]
fixed
