### ISSUE TITLE
broken links in docs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/pyphetools#119]
https://monarch-initiative.github.io/pyphetools/

This section:

How to use [pyphetools classes](https://monarch-initiative.github.io/pyphetools/user-guide/jupyter.md) to convert tabular data (e.g., supplemental tables) to phenopackets
Information for [developers](https://monarch-initiative.github.io/pyphetools/developers/developers/)

Both links don't resolve to a proper mkdocs page

**Comment by pnrobinson** [comment]
thanks! Fixed with latest release
