### ISSUE TITLE
Full Disease ID

### ISSUE THREAD

**Issue by lnrekerle** [monarch-initiative/pyphetools#15]
I noticed in Example_1_(rowwise_table)_MAPK8IP3.ipynb that the disease does not have the ID type (OMIM, MONDO, etc) 

```
disease_id = '618443'
disease_name = 'Neurodevelopmental disorder with or without variable brain abnormalities'

encoder.set_disease(disease_id=disease_id, label=disease_name)
```

This is affecting my code for genophenocorr since I am using the data as sample data. 
Thank you!!

**Comment by pnrobinson** [comment]
fixed this
