### ISSUE TITLE
Error when installing Jupyter kernel

### ISSUE THREAD

**Issue by hansenp** [monarch-initiative/pyphetools#29]
If I follow the [instructions to install `pyphetools`](https://monarch-initiative.github.io/pyphetools/installation.html#installation), then I get the following error when installing the Jupyter kernel:
```
$ python -m ipykernel install --name "ppt_env" --display-name "ppt_env"
[Errno 13] Permission denied: '/usr/local/share/jupyter'
```

If I run the following command instead then I don't get this error.
```
$ python -m ipykernel install --name "ppt_env" --display-name "ppt_env" --user
Installed kernelspec ppt_env in /Users/hansep/Library/Jupyter/kernels/ppt_env
```
I would suggest changing the documentation accordingly.

**Comment by pnrobinson** [comment]
Thanks for pointing this out -- I have changed the instructions!

**Comment by hansenp** [comment]
I'm reopening this issue because the [related documentation is unchanged](https://monarch-initiative.github.io/pyphetools/developers/installation/) and I'm getting the same error as described above. A solution to the problem is also described above.
