### ISSUE TITLE
add NLP/text mining lib?

### ISSUE THREAD

**Issue by ldingemans** [monarch-initiative/pyphetools#7]
I am looking into this tool to see how it works and use it to extract data from supplemental tables, was thinking about adding some notebooks for specific PMIDs, etc.

However, while I get the idea for supplemental tables, usually there is (much) more additional information available in (supplemental) text (for instance in the paper I was looking into for _SMARCB1_, [https://www.sciencedirect.com/science/article/pii/S1098360021010108?via%3Dihub](https://www.sciencedirect.com/science/article/pii/S1098360021010108?via%3Dihub): the clinical table lacks the clinical information the general text has)

Of course, there has been work on using NLP/text mining to extract HPO terms from text, and with the renewed interest in GTP-3/4/ChatGPT I think we will see some massive progress on this in 2023. I tried a couple that are already out there and was pretty impressed with PhenoTagger ([https://github.com/ncbi-nlp/PhenoTagger](https://github.com/ncbi-nlp/PhenoTagger) and [https://huggingface.co/spaces/lingbionlp/PhenoTaggger-Demo](https://huggingface.co/spaces/lingbionlp/PhenoTaggger-Demo)) on which I noticed @pnrobinson is an author as well.

I was thinking of maybe adding a module or something to this package that adds functionality to extract HPO terms from text (will probably be a pretty easy implementation of API calls to PhenoTagger), but not sure if that is wanted here? On one hand, it is something totally different from the current data extraction from table thing (argument to not add it here), but it does have the same aim of converting a paper into HPO terms/phenopackets and therefore could complement the current approach. So I am not sure?

If that is something that could be of value, do let me know, and I will start implementing it

**Comment by pnrobinson** [comment]
Hi Lex!
currently, an extremely simple NLP is implemented in the Python code. PhenoTagger works well indeed. We have also been working on a new tool that at least for some kinds of clinical text may be better (https://github.com/monarch-initiative/fenominal). I guess the question is what our goal is for this python package. I would suggest for the first clustering project probably we should just get things to aq good 80% level and then we can continue to improve things. I am a little concerned that the supplements are so heterogeneous and we probably should not try to implement a tool that will work perfectly or all or even most of the supplements...so maybe we should just try to encode 20 genes with this tool, understand the challenges and then implement stuff that will make say 50% of the supplements easy, and another 30% of the supplements relatively easy, etc?

**Comment by pnrobinson** [comment]
closing as not planned in immediate future.
