### ISSUE TITLE
Improve ergonomics

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/pyphetools#86]
Add model objects for the most commonly used elements of the Phenopacket Schema support autocompletion, and to improve ergonomics. 

The ergonomics improvements should include something similar to Phenopacket tools, where we can set sex, karyotype, age, vital status, etc. directly on the individual.

**Comment by pnrobinson** [comment]
closing because of PR #92 
Let's see how this interacts with the rest of the library and then we can extend as needed.
